### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by adadada19** [rejuvena/terraprisma#1]
What i have done wrong? 
Done what was in readme file
![image](https://user-images.githubusercontent.com/74622642/152699695-b4e8ac96-1a66-47df-8849-afd38e39a68a.png)

**Comment by steviegt6** [comment]
Hi! Not sure where you found this, but the project was not functioning at the time. I have gotten around to finishing it today.

**Comment by adadada19** [comment]
i can't start release one now, i think i do something wrong still

**Comment by steviegt6** [comment]
> i can't start release one now, i think i do something wrong still

Please make a new issue detailing your current problem.
